datasets: 
  - /home/katarzynam/home/katarzynam/data/data_X_y_scaled_seed_3.npz
model_dir: /home/katarzynam/models
model: 
  - cgan_240831_19354794
  - cgan_240831_19481285
  - cgan_240901_23564599
model_labels:
  - $\lambda_{fftmse}=1.0$
  - $\lambda_{mse}=1.0$
  - FFT Discriminator
cp: [500,1000,1500,2000]  
batch_size: 1000
compute_wasserstein: true
compute_fft: true
compute_mse: true
compute_cosine_similarity: true
compute_fatigue: true
compute_generator_diversity: true
compute_wavelets: true
plot_samples: true
fatigue_sc: 90.0
wavelet_function: db4

range_SH: null
range_TI: null
range_U: null
range_DIR: null
range_D: null
