cp_freq: 100
t_len: 300
lr_G: 0.0001
lr_D: 0.0001
n_epochs: 10000
batch_size: 512
log_freq: 200
sa_weights: false
datasets: 
  - /home/katarzynam/home/katarzynam/data/data_X_y_scaled_seed_1.npz
  - /home/katarzynam/home/katarzynam/data/data_X_y_scaled_seed_2.npz
increase_nr_samples: false

X_vars:
  - Rotor speed
  - Nacelle fore-aft acceleration
  - Nacelle side-side acceleration
  - Rotor azimuth angle
  - Blade 1 pitch angle
  - Generator speed
  - HSS torque
  - Electrical power

Y_vars:
  - Tower My (at 0.00m)

add_info_to_X: true
range_SH: null
range_TI: null
range_U: null
range_DIR: null
range_D: null
discr_input: "ts"

model_preload: null
model_preload_cp: 1000
model_preload_nr_freeze_epochs: 50
model_dir: '/home/katarzynam/models'
noise_vector_dim: 10
hidden_dim: 100

lambda_mse: 0.0
lambda_fftwass: 0.0
lambda_fftmse: 0.0